### ISSUE TITLE
Characters can get escaped when they should not be with javaproperties.dump(properties, file)

### ISSUE THREAD

**Issue by cosmicaug** [jwodder/javaproperties#10] opened 2020-09-21 20:08 UTC
If we do something like:

`properties = {
    'key=1': 'value = 1',
    'key=2': 'value = 2',
    'key=3': 'value = 3',
}

try:
    with open(file, 'w') as f:
        javaproperties.dump(properties, f)
except IOError as e:
    print(e)`

We should be seeing the first '=' (associated with the keys) get escaped but not the second one (associated with the values), I believe (if '=' is being used as the separator). Currently, both get escaped.

**Comment by jwodder** [comment] 2020-09-21 20:13
Escaping both `=`'s is the intended behavior, and there's nothing wrong with it.  Copying my reply from issue #3, which this issue is basically a duplicate of:

---

The library's `dumps()` function mimics the behavior of `java.util.Properties`'s `store()` method, [whose documentation states in part](https://docs.oracle.com/javase/10/docs/api/java/util/Properties.html#store(java.io.Writer,java.lang.String)):

> The key and element characters #, !, =, and : are written with a preceding backslash to ensure that they are properly loaded.

I don't believe this is actually required for proper loading, but I do it anyway in order to match Java's behavior.  Escaping arbitrary characters in this way is acceptable, as, [to quote the documentation for the `load()` method](https://docs.oracle.com/javase/10/docs/api/java/util/Properties.html#load(java.io.Reader)):

> The method does not treat a backslash character, `\`, before a non-valid escape character as an error; the backslash is silently dropped. For example, in a Java string the sequence `"\z"` would cause a compile time error. In contrast, this method silently drops the backslash. Therefore, this method treats the two character sequence `"\b"` as equivalent to the single character `'b'`.

So `\=` in an element is equivalent to `=`.

**Closed** 2020-11-27 21:10 UTC
Labels: duplicate
